version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/vcap/data/registry
http:
    addr: :8080
    headers:
      X-Content-Type-Options: [nosniff]
    tls:
      certificate: /var/vcap/registry/certs/nginx.crt
      key: /var/vcap/registry/certs/nginx.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
#proxy:
#  remoteurl: http://wdxxs2z.m.alauda.cn
